import { z } from 'zod';

export const tradeSchema = z.object({
  id: z.number(),
  symbol: z.string(),
  type: z.enum(['BUY', 'SELL']),
  status: z.enum(['COMPLETED', 'PENDING', 'CANCELLED']),
  quantity: z.number(),
  price: z.number(),
  entryPrice: z.number().optional(),
  exitPrice: z.number().optional(),
  timestamp: z.string(),
  pnl: z.number().optional(),
  pnlPercentage: z.number().optional(),
  exchange: z.string(),
  orderType: z.enum(['MARKET', 'LIMIT', 'STOP', 'STOP_LIMIT']),
  notes: z.string().optional(),
  tags: z.array(z.string()).optional(),
  plan: z.string().optional(),
  execution: z.string().optional(),
});

export type Trade = z.infer<typeof tradeSchema>;

export const mockTrades: Trade[] = [
  {
    id: 1,
    symbol: 'AAPL',
    type: 'BUY',
    status: 'COMPLETED',
    quantity: 10,
    price: 178.72,
    entryPrice: 178.72,
    exitPrice: 180.95,
    timestamp: '2025-01-15T09:30:45Z',
    pnl: 22.3,
    pnlPercentage: 1.25,
    exchange: 'NASDAQ',
    orderType: 'MARKET',
    notes: 'Earnings play',
    tags: ['tech', 'earnings'],
    plan: 'Buy before earnings, target 185',
    execution: 'Executed as planned, took profits at target',
  },
  {
    id: 2,
    symbol: 'MSFT',
    type: 'SELL',
    status: 'COMPLETED',
    quantity: 5,
    price: 410.34,
    entryPrice: 395.22,
    exitPrice: 410.34,
    timestamp: '2025-01-15T10:15:30Z',
    pnl: 75.6,
    pnlPercentage: 3.82,
    exchange: 'NASDAQ',
    orderType: 'LIMIT',
    notes: 'Taking profits before earnings',
    tags: ['tech', 'profit-taking'],
    plan: 'Sell at resistance level 410',
    execution: 'Perfect execution at planned resistance',
  },
  {
    id: 3,
    symbol: 'TSLA',
    type: 'BUY',
    status: 'PENDING',
    quantity: 3,
    price: 188.50,
    timestamp: '2025-01-15T11:45:22Z',
    exchange: 'NASDAQ',
    orderType: 'LIMIT',
    notes: 'Looking for support at 200-day MA',
    tags: ['tech', 'ev'],
    plan: 'Buy at 200-day MA support',
    execution: 'Waiting for price to reach support level',
  },
  {
    id: 4,
    symbol: 'AMZN',
    type: 'SELL',
    status: 'CANCELLED',
    quantity: 8,
    price: 175.20,
    timestamp: '2025-01-15T13:10:05Z',
    exchange: 'NASDAQ',
    orderType: 'STOP_LIMIT',
    notes: 'Cancelled due to market reversal',
    plan: 'Sell if breaks below 175 support',
    execution: 'Cancelled as market showed strength',
  },
  {
    id: 5,
    symbol: 'NVDA',
    type: 'BUY',
    status: 'COMPLETED',
    quantity: 15,
    price: 820.40,
    entryPrice: 820.40,
    exitPrice: 815.25,
    timestamp: '2025-01-15T14:30:15Z',
    pnl: -77.25,
    pnlPercentage: -0.63,
    exchange: 'NASDAQ',
    orderType: 'MARKET',
    tags: ['tech', 'semiconductor', 'AI'],
    plan: 'Buy breakout above 820',
    execution: 'Entered too late, stopped out',
  },
  {
    id: 6,
    symbol: 'GOOGL',
    type: 'BUY',
    status: 'COMPLETED',
    quantity: 12,
    price: 142.38,
    entryPrice: 142.38,
    exitPrice: 144.72,
    timestamp: '2025-01-15T15:20:10Z',
    pnl: 28.08,
    pnlPercentage: 1.64,
    exchange: 'NASDAQ',
    orderType: 'MARKET',
    tags: ['tech', 'AI'],
    plan: 'Buy at trend line support',
    execution: 'Good entry at support, quick profit',
  },
  {
    id: 7,
    symbol: 'META',
    type: 'SELL',
    status: 'COMPLETED',
    quantity: 7,
    price: 475.72,
    entryPrice: 440.15,
    exitPrice: 475.72,
    timestamp: '2025-01-16T09:45:30Z',
    pnl: 248.99,
    pnlPercentage: 8.08,
    exchange: 'NASDAQ',
    orderType: 'LIMIT',
    notes: 'Taking profits after strong rally',
    tags: ['tech', 'social-media'],
    plan: 'Hold until earnings, sell before announcement',
    execution: 'Sold at peak before earnings release',
  },
  {
    id: 8,
    symbol: 'JPM',
    type: 'BUY',
    status: 'PENDING',
    quantity: 20,
    price: 172.80,
    timestamp: '2025-01-16T10:55:45Z',
    exchange: 'NYSE',
    orderType: 'LIMIT',
    notes: 'Banking sector looks undervalued',
    tags: ['finance', 'value'],
    plan: 'Buy at support, target 180',
    execution: 'Waiting for entry price',
  },
  {
    id: 9,
    symbol: 'COIN',
    type: 'SELL',
    status: 'COMPLETED',
    quantity: 5,
    price: 218.50,
    entryPrice: 240.25,
    exitPrice: 218.50,
    timestamp: '2025-01-16T11:30:15Z',
    pnl: -108.75,
    pnlPercentage: -9.05,
    exchange: 'NASDAQ',
    orderType: 'STOP',
    notes: 'Stop loss triggered',
    tags: ['crypto', 'stop-loss'],
    plan: 'Hold above 240, stop at 220',
    execution: 'Stopped out as planned',
  },
  {
    id: 10,
    symbol: 'AMD',
    type: 'BUY',
    status: 'COMPLETED',
    quantity: 25,
    price: 162.40,
    entryPrice: 162.40,
    exitPrice: 166.75,
    timestamp: '2025-01-16T14:15:30Z',
    pnl: 108.75,
    pnlPercentage: 2.68,
    exchange: 'NASDAQ',
    orderType: 'MARKET',
    tags: ['tech', 'semiconductor'],
    plan: 'Buy pullback to 160-165 zone',
    execution: 'Good entry on pullback, quick reversal',
  },
];

// Generate mock chart data for performance visualization
export const generatePerformanceData = (days = 30) => {
  const data = [];
  let cumulativePnL = 0;
  const startDate = new Date();
  startDate.setDate(startDate.getDate() - days);

  for (let i = 0; i < days; i++) {
    const date = new Date(startDate);
    date.setDate(startDate.getDate() + i);
    
    // Random daily PnL between -500 and 500
    const dailyPnL = Math.round((Math.random() * 1000 - 500) * 100) / 100;
    cumulativePnL += dailyPnL;
    
    data.push({
      date: date.toISOString().split('T')[0],
      dailyPnL,
      cumulativePnL: Math.round(cumulativePnL * 100) / 100,
    });
  }
  
  return data;
};

export const performanceData = generatePerformanceData();